### ISSUE TITLE
Unexpected missing of self

### ISSUE THREAD

**Issue by akvariefisk** [giuscris/formwork#514]
### Description

I was on my way to edit the page from admin panel. 

**Formwork**: 2.0.0-beta.1
**Php**: 8.3.4
**OS**: Windows
**SAPI**: apache2handler

### Stack Trace
```
Uncaught RuntimeException: Unexpected missing of self in C:\laragon\www\formwork\formwork\src\Pages\Traits\PageTraversal.php:261

#0 C:\laragon\www\formwork\formwork\src\Pages\Traits\PageTraversal.php(244): Formwork\Pages\Page->index()
#1 C:\laragon\www\formwork\panel\views\pages\editor.php(22): Formwork\Pages\Page->previousSibling()
#2 C:\laragon\www\formwork\formwork\src\View\Renderer.php(30): include('C:\\laragon\\www\\...')
#3 C:\laragon\www\formwork\formwork\src\View\Renderer.php(20): Closure->Formwork\View\{closure}('C:\\laragon\\www\\...', Array)
#4 C:\laragon\www\formwork\formwork\src\View\View.php(242): Formwork\View\Renderer::load('C:\\laragon\\www\\...', Array, Object(Formwork\View\View))
#5 C:\laragon\www\formwork\formwork\src\View\View.php(132): Formwork\View\View->output()
#6 C:\laragon\www\formwork\formwork\src\Panel\Controllers\AbstractController.php(236): Formwork\View\View->render()
#7 C:\laragon\www\formwork\formwork\src\Panel\Controllers\PagesController.php(218): Formwork\Panel\Controllers\AbstractController->view('pages.editor', Array)
#8 C:\laragon\www\formwork\formwork\src\Services\Container.php(68): Formwork\Panel\Controllers\PagesController->edit(Object(Formwork\Router\RouteParams))
#9 C:\laragon\www\formwork\formwork\src\Router\Router.php(186): Formwork\Services\Container->call(Object(Closure))
#10 C:\laragon\www\formwork\formwork\src\App.php(131): Formwork\Router\Router->dispatch()
#11 C:\laragon\www\formwork\index.php(12): Formwork\App->run()
#12 {main}

**Comment by akvariefisk** [comment]
Sorry for my double post . Seems that windows makes this error . Fresh install from Github.

**Comment by giuscris** [comment]
Thank you for reporting @akvariefisk. I'll be able to check on a windows machine by the end of the week.

**Comment by giuscris** [comment]
Solved, see https://github.com/getformwork/formwork/issues/513#issuecomment-2143891215
